library(shiny)
library(shinydashboard)
library(readxl)
animals <- read_csv('./data/finalAnimals.csv')
locations <- read_csv('./data/locations.csv')
Turtles = read_excel('./data/turtle_chart3.xlsx', skip = 1)